package com.uniskare.eureka_skill.controller;

import com.uniskare.eureka_skill.entity.Skill;
import com.uniskare.eureka_skill.repository.SkillRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(path="/skill")
public class SkillController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SkillRepo skillRepo;


    @GetMapping(path="/all")
    public Iterable<Skill> getAllSkills() {
        // This returns a JSON or XML with the users
        return skillRepo.findAll();
    }
//    @RequestMapping("/")
//    public String index() {
//        return "Greetings from Spring Boot!";
//    }
}
