package com.uniskare.eureka_skill;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@Controller
@RequestMapping(path="/skill")
public class SkillController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SkillRepository skillRepository;


    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Skill> getAllSkills() {
        // This returns a JSON or XML with the users
        return skillRepository.findAll();
    }
//    @RequestMapping("/")
//    public String index() {
//        return "Greetings from Spring Boot!";
//    }
}
