server:
  port: 8899
  ssl:
    key-store: classpath:1913993_www.uniskare.xyz.pfx
    key-store-password: nlKLbOq3
    key-store-type: PKCS12

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://49.235.255.145:8991/eureka/,http://49.234.96.26:8991/eureka/


spring:
  application:
    name: gateway-provider
  cloud:
    gateway:
      routes:
        - id: api-user-service
          uri: http://49.234.96.26:7956
          predicates:
            - Path=/user/**


