server:
  port: 7955

spring:
  application:
    name: skill-provider
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://49.235.255.145:8761/eureka/