server:
  port: 8991



spring:
  application:
    name: Uniskare-Eureka-Server
eureka:
  server:
    renewalPercentThreshold: 0.6
  client:
    register-with-eureka: true
    fetch-registry: true
---
spring:
  profiles: peer1
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
        - eth.*
        - lo
      preferredNetworks:
        - 49.235.255.145
eureka:
  instance:
    hostname: Uniskare1
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://49.235.255.145:8991/eureka/



---
spring:
  profiles: peer2
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker
        - eth.*
        - lo
      preferredNetworks:
        - 49.234.96.26
eureka:
  instance:
    hostname: Uniskare2
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://Uniskare1:8991/eureka/
#eureka:
#  server:
#    # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
#    eviction-interval-timer-in-ms: 5000
#  client:
#    # eureka client间隔多久去拉取服务注册信息 默认30s
#    registry-fetch-interval-seconds: 30
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:${server.port}/eureka/}
#  instance:
#    # 心跳间隔时间，即发送一次心跳之后，多久在发起下一次（缺省为30s）
#    lease-renewal-interval-in-seconds: 10
#    # 在收到一次心跳之后，等待下一次心跳的空档时间，大于心跳间隔即可，即服务续约到期时间（缺省为90s）
#    lease-expiration-duration-in-seconds: 15
#    instance-id: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}:${server.port}@${random.long(1000000,9999999)}
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
