server:
  port: 7956

spring:
  application:
    name: order-provider
  rabbitmq:
    host: 121.199.0.20
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: MANUAL
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://49.235.255.145:8761/eureka/
