server:
  port: 8899
  ssl:
    key-store: classpath:1913993_www.uniskare.xyz.pfx
    key-store-password: nlKLbOq3
    key-store-type: PKCS12
    enabled: true

eureka:
  instance:
    ip-address: 47.102.158.185
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://49.235.255.145:8991/eureka/,http://49.234.96.26:8991/eureka/





spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
      - id: user-module
        uri: lb:http://user-provider
        predicates:
        - Path=/user/**

      - id: order-module
        uri: lb:http://order-provider
        predicates:
        - Path=/order/**

      - id: skill-module
        uri: lb:http://skill-provider
        predicates:
        - Path=/skill/**

      - id: comm-module
        uri: lb:http://communication-provider
        predicates:
        - Path=/comm/**
      discovery:
        locator:
          enabled: true




