server:
  port: 7956

spring:
  application:
    name: user-provider
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://49.235.255.145:8991/eureka/,http://49.234.96.26:8991/eureka/
