server:
  port: 7909

spring:
  application:
    name: server-skill-provider
eureka:
  client:
    fetch-registry: true
    service-url:
        defaultzone: http://49.235.255.145:8761, http://49.234.96.26:8761
