server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultzone: http://49.235.255.145:8761/eureka,http://49.234.96.26:8761/eureka

spring:
  application:
    name: Uniskare-Eureka-Server
