package com.uniskare.eureka_skill.service.impl;

import com.uniskare.eureka_skill.entity.Skill;
import com.uniskare.eureka_skill.repository.SkillRepo;
import com.uniskare.eureka_skill.service.SkillService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.stereotype.Service;

import org.springframework.data.domain.Pageable;

import java.util.Optional;
/**
 * @author : Bhy
 * @description ：
 */
@Service
public class SkillServiceImpl implements SkillService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SkillRepo skillRepo;

    @Override
    public Skill save(Skill skill) {
        return skillRepo.save(skill);
    }

    @Override
    public Page<Skill> findAll(Pageable pageable) {
        return skillRepo.findAll(pageable);
    }

    @Override
    public Optional<Skill> findById(int skillId) {
        return skillRepo.findById(skillId);
    }

    @Override
    public void deleteById(int skillId) {
        skillRepo.deleteById(skillId);
    }

    @Override
    public void updateSkill(Skill skill) {
        Optional<Skill> oldSkillOpt = skillRepo.findById(skill.getSkillId());
        if(oldSkillOpt.isPresent()) {
            Skill oldSkill = oldSkillOpt.get();
        }
        // Todo:更新哪些内容、
        // skillRepo.save(oldSkill);
    }

}
